pipeline {
    agent any

    tools {
        maven 'maven3.6.2'
        jdk 'jdk1.8u342'
    }

    environment {
        SIT_ROOT_CREDENTIALS=credentials('TTS_SIT_ROOT')
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'mvn clean package -DskipTests -Pjar,lab-tts -U'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'cp target/*jar target/smart-light.jar'
                sh 'ansible-playbook -e ansible_become_pass=$SIT_ROOT_CREDENTIALS_PSW -i /var/jenkins_home/ansible/inventory playbook.yaml'
            }
        }
    }
}
