version: '3.8'

services:
  jenkins:
    build: .
    ports:
      - "8087:8080"
      - "50000:50000"
    volumes:
      - "jenkins_volumes:/var/jenkins_home:rw"
    environment:
      - TZ=Asia/Taipei
    restart: always  
    container_name: jenkins

volumes:
  jenkins_volumes:
